// Export Module

const Exporter = {
    formatCurrency(value) {
        return '$' + value.toLocaleString(undefined, {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2
        });
    },

    formatPercent(value) {
        return value.toFixed(2) + '%';
    },

    exportSimpleToCSV(results) {
        let csv = 'ROI Calculator Results\n\n';
        csv += 'Metric,Value\n';
        csv += 'ROI Percentage,' + this.formatPercent(results.roi) + '\n';
        csv += 'Net Profit,' + this.formatCurrency(results.profit) + '\n';
        csv += 'Total Revenue,' + this.formatCurrency(results.revenue) + '\n';
        csv += 'Total Costs,' + this.formatCurrency(results.costs) + '\n';
        csv += 'Time Period,' + results.periodMonths + ' months\n';
        csv += 'Payback Period,' + results.paybackMonths.toFixed(2) + ' months\n';
        csv += 'Annualized ROI,' + this.formatPercent(results.annualizedRoi) + '\n';
        csv += '\nExported on,' + new Date().toLocaleString() + '\n';

        this.downloadCSV(csv, 'roi-calculator-results.csv');
    },

    exportAdvancedToCSV(scenarios) {
        let csv = 'Advanced ROI Analysis - Scenario Comparison\n\n';
        csv += 'Scenario,NPV ($),IRR (%),ROI (%),Payback Period (years),Total Benefits ($),Total Costs ($)\n';

        scenarios.forEach(scenario => {
            csv += `${scenario.name},${this.formatCurrency(scenario.results.npv)},`;
            csv += `${this.formatPercent(scenario.results.irr)},`;
            csv += `${this.formatPercent(scenario.results.roi)},`;
            csv += `${scenario.results.paybackPeriod.toFixed(2)},`;
            csv += `${this.formatCurrency(scenario.results.totalBenefits)},`;
            csv += `${this.formatCurrency(scenario.results.totalCosts)}\n`;
        });

        csv += '\nExported on,' + new Date().toLocaleString() + '\n';

        this.downloadCSV(csv, 'advanced-roi-analysis.csv');
    },

    downloadCSV(content, filename) {
        const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        const url = URL.createObjectURL(blob);

        link.setAttribute('href', url);
        link.setAttribute('download', filename);
        link.style.visibility = 'hidden';

        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    },

    async exportSimpleToPDF(results) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Title
        doc.setFontSize(24);
        doc.setTextColor(79, 70, 229);
        doc.text('ROI Calculator Results', 105, 20, { align: 'center' });

        // Subtitle
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text('Business Case Analysis Report', 105, 28, { align: 'center' });

        // Line
        doc.setDrawColor(79, 70, 229);
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        let yPosition = 45;

        // Key Metrics
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text('Key Metrics', 20, yPosition);
        yPosition += 10;

        // ROI Card
        this.pdfCard(doc, 'ROI Percentage', this.formatPercent(results.roi), 20, yPosition);
        yPosition += 30;

        // Profit Card
        this.pdfCard(doc, 'Net Profit', this.formatCurrency(results.profit), 20, yPosition);
        yPosition += 30;

        // Detailed Results
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Detailed Breakdown', 20, yPosition);
        yPosition += 10;

        const details = [
            ['Metric', 'Value'],
            ['Total Revenue', this.formatCurrency(results.revenue)],
            ['Total Costs', this.formatCurrency(results.costs)],
            ['Time Period', results.periodMonths + ' months'],
            ['Payback Period', results.paybackMonths.toFixed(2) + ' months'],
            ['Annualized ROI', this.formatPercent(results.annualizedRoi)]
        ];

        this.pdfTable(doc, details, 20, yPosition);
        yPosition += 80;

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by ShangLabs ROI Calculator', 105, 280, { align: 'center' });
        doc.text('Exported on ' + new Date().toLocaleString(), 105, 285, { align: 'center' });

        doc.save('roi-calculator-results.pdf');
    },

    async exportAdvancedToPDF(scenarios) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Title
        doc.setFontSize(24);
        doc.setTextColor(79, 70, 229);
        doc.text('Advanced ROI Analysis', 105, 20, { align: 'center' });

        // Subtitle
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text('Multi-Scenario Comparison Report', 105, 28, { align: 'center' });

        // Line
        doc.setDrawColor(79, 70, 229);
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        let yPosition = 45;

        // Executive Summary
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Executive Summary', 20, yPosition);
        yPosition += 10;

        const bestScenario = scenarios.reduce((best, current) =>
            current.results.npv > best.results.npv ? current : best
        );

        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        const summary = `The best performing scenario is "${bestScenario.name}" with an NPV of ${this.formatCurrency(bestScenario.results.npv)} and ROI of ${this.formatPercent(bestScenario.results.roi)}.`;
        const splitSummary = doc.splitTextToSize(summary, 170);
        doc.text(splitSummary, 20, yPosition);
        yPosition += 25;

        // Scenario Comparison Table
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Scenario Comparison', 20, yPosition);
        yPosition += 10;

        const tableData = [
            ['Scenario', 'NPV ($)', 'IRR (%)', 'ROI (%)', 'Payback (yr)']
        ];

        scenarios.forEach(scenario => {
            tableData.push([
                scenario.name,
                this.formatCurrency(scenario.results.npv),
                this.formatPercent(scenario.results.irr),
                this.formatPercent(scenario.results.roi),
                scenario.results.paybackPeriod.toFixed(2)
            ]);
        });

        this.pdfTable(doc, tableData, 20, yPosition);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by ShangLabs ROI Calculator', 105, 280, { align: 'center' });
        doc.text('Exported on ' + new Date().toLocaleString(), 105, 285, { align: 'center' });

        doc.save('advanced-roi-analysis.pdf');
    },

    pdfCard(doc, label, value, x, y) {
        // Card background
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(x, y, 170, 22, 3, 3, 'F');

        // Label
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(label, x + 10, y + 12);

        // Value
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(79, 70, 229);
        doc.text(value, x + 160, y + 12, { align: 'right' });
        doc.setFont(undefined, 'normal');
    },

    pdfTable(doc, data, x, y) {
        const cellWidth = 34;
        const cellHeight = 8;
        const rowGap = 2;

        data.forEach((row, rowIndex) => {
            row.forEach((cell, colIndex) => {
                const cellX = x + (colIndex * cellWidth);
                const cellY = y + (rowIndex * (cellHeight + rowGap));

                // Header row styling
                if (rowIndex === 0) {
                    doc.setFillColor(241, 245, 249);
                    doc.roundedRect(cellX, cellY, cellWidth, cellHeight, 2, 2, 'F');
                    doc.setFontSize(9);
                    doc.setFont(undefined, 'bold');
                    doc.setTextColor(30, 41, 59);
                } else {
                    doc.setFontSize(9);
                    doc.setFont(undefined, 'normal');
                    doc.setTextColor(60, 60, 60);
                }

                // Center text in cells
                const cellWidthAdjusted = cellWidth - 4;
                doc.text(cell, cellX + cellWidth / 2, cellY + 5, { align: 'center', maxWidth: cellWidthAdjusted });
            });
        });
    }
};
